### ISSUE TITLE
I can't export selected users

### ISSUE THREAD

**Issue by AbdoALPOP** [Rengage-co/blocfree#9]
Export users' action not working, check [here](https://drive.google.com/file/d/1DgIGWtUQ0L_quF1NN-UXEi8KUOsWugsF/view?usp=sharing).

**Comment by jackyfeng1015** [comment]
Which fields will be export? @akram-rengage

**Comment by akram-rengage** [comment]
@jackyfeng1015 name and email

**Comment by blake-bai** [comment]
How to name the exported file? @akram-rengage

**Comment by akram-rengage** [comment]
just called it team_members.csv
